FROM rust:1.95-bookworm AS builder
WORKDIR /src
COPY rust ./rust
RUN cd rust && cargo build --release -p hunterd

FROM gcr.io/distroless/cc-debian12
COPY --from=builder /src/rust/target/release/hunterd /usr/local/bin/hunterd
ENTRYPOINT ["/usr/local/bin/hunterd"]
