[package]
name = "execution"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
filter_stack = { path = "../filter_stack" }
metrics = { path = "../metrics" }
rpc_pool = { path = "../rpc_pool" }
sh_sniffer = { path = "../sh_sniffer" }
tx_builder = { path = "../tx_builder" }
wallet = { path = "../wallet" }
